### ISSUE TITLE
Ubuntu Rebuild Instructions

### ISSUE THREAD

**Issue by tyndyll** [hardtware/DC2#13]
I've had to replace the SSD. Is it possible to get instructions to rebuild a new disk?

**Comment by remonlam** [comment]
I don't think that it has ever been published, however if you need a copy of the image? please let me know...

**Comment by dickhardt** [comment]
Here are the directions I got from my friend that built the image

1. grab the ubuntu-desktop x86_64 14.04 LTS ISO
2. install it onto another usb drive, not the DC2 one, using one of the ubuntu USB media installers (either from w/in another ubuntu box, or there’s a windows media prep tool, or something else. http://www.ubuntu.com/download/desktop/create-a-usb-stick-on-ubuntu )
	** Note that step #2 was not easy, especially when I was using the ubuntu-server ISO instead of the desktop. Desktop ISO worked much better, but I’m not sure all the media prep programs on that page above are bug free. **

3. all defaults during the install, hostname is “dc2”, username is “dc2” i wrote down that the pw was “ubuntu” but I think you changed the default username and password. I enabled automatic security updates (again, I think this is probably the default setting).
4. this should set up a dhcp by default, I don’t think I enabled IPv6 or if I did I just left it as defaults
5. no special packages during install
6. On first boot my notes say I installed packages for docker and node. I don’t know if I needed to install the bonjour stuff (avahi-* packages) or if I was already enabled by default. I don’t know if I needed to enable docker or node to run on boot, but that would be another command to enable it on boot ( http://askubuntu.com/questions/9382/how-can-i-configure-a-service-to-run-at-startup explains).
7. I disabled the X11/graphical boot (using these instructions http://www.htpcbeginner.com/force-ubuntu-boot-into-terminal/ )
8. I manually updated all packages (“sudo apt-get update ; sudo apt-get upgrade ; sudo apt-get dist-upgrade ; sudo apt-get autoremove”) then reboot if it installed a new kernel, or if it says to reboot.
9. I probably installed the openssh-server package (“sudo apt-get install openssh-server”).
10. I did some checks on the permissions of the .ssh directory to make sure we’d be able to ssh in, then tested it from remote (“ssh dc2@dc2.local”).
11. I did some final cleanup (removing files I had created, .git dirs, .bash_history, etc… but this isn’t necessary unless you’re re-creating a new gold image).

**Comment by tyndyll** [comment]
Finally got round to trying this. There seems to be something weird with the EFI boot - it seems like it is expecting a certain GUID for the disk (as set up in the boot options under the name ubuntu)

Would it be possible to get the original image

**Comment by tyndyll** [comment]
@remonlam Would it be possible to get a copy of the image?

**Comment by remonlam** [comment]
@tyndyll sure let me find a way to share it

**Comment by remonlam** [comment]
Hope this one works!
https://we.tl/DnDh3lStUA
